### ISSUE TITLE
Reevaluate usage of ctrl commands

### ISSUE THREAD

**Issue by la-magra** [mattbrictson/bundle_update_interactive#16]
Hello, loving your project, you just perfectly solved a major usability issue of bundler.

Just 2 things, 
be aware that `ctrl-a` is a very popular tmux prefix key and will conflict with this command usage,
and this is more of a nitpick but using `ctrl-r` on a command line util feels strange (it's reverse search).

I would propose switching to `shift-a` and `shift-r` or even just `a` and `r`.

**Comment by mattbrictson** [comment]
@la-magra thanks for the feedback! I am not a tmux user, so this issue is a blindspot for me.

Point taken on `ctrl-r` – I agree this is a weird choice given that this combination is very commonly used for reverse-search in readline.

For background, I am using `ctrl-a` and `ctrl-r` simply because these are the default key bindings provided by [tty-prompt](https://github.com/piotrmurach/tty-prompt), which is the library I am using to render the multi-select menu. It seems like that library decided on `ctrl-a` and `ctrl-r` somewhat arbitrarily. See: https://github.com/piotrmurach/tty-prompt/issues/140

So I am definitely open to changing these.

It looks like `yarn upgrade-interactive` (where I have taken a lot of inspiration) uses just `a` and `i` without any modifier. What do you think of following that convention?

**Comment by la-magra** [comment]
In general using `ctrl-anything` on a command line util (and not taking over signal control) is just asking for trouble.

I would be OK with using `a`ll and `i`nvert (similar to `yarn upgrade-interactive` (the yarn 1.22.21 version. I have some... issues... with the yarn berry (4.*.*) version)).

From an ergonomic standpoint perhaps `r`everse would be better, since everything is near your left hand while you use the arrow keys with the right.

Also, if I may, I got two requests (I'll open new issues if you want):

- add a `latest` column after `from -> to`. 
  Perhaps out of scope/scope creep, but would allow to quickly check if you can update further instead of also running `bundle outdated` then going fishing for changelogs in a search engine. 
  Could be implemented as an argument? `--show-latest` maybe?
  It would also be similar to how `bundle outdated` shows its info (but in the correct order).
![image](https://github.com/user-attachments/assets/7f778651-142c-4aeb-879f-1857f6590ba7)


- add colors to the keys (if possible, just a good usability practice) like in this example (`yarn upgrade-interactive` (yarn 4.3.1)):
![image](https://github.com/user-attachments/assets/f0fda88f-fe6c-4bbb-972d-70ec7b06c2a0)

**Comment by mattbrictson** [comment]
Noted! I am leaning towards `a` and `r` for the reasons you mentioned.

Yes, please open new issues for the other enhancements. Regarding `latest`, there is some related discussion in #13 about somehow indicating gems that are being held back from their latest versions. I think your suggestion is probably complementary, but maybe there is a way to combine those features since they are serving similar goals.

Thanks again for the feedback!
