### ISSUE TITLE
Ability to skip finding changelogs

### ISSUE THREAD

**Issue by vfonic** [mattbrictson/bundle_update_interactive#66]
`bundle outdated` is exponentially faster than `bundle ui` because `bundle ui` searches for a CHANGELOG for each gem that needs to be updated. Would be good to have an option to skip finding changelogs or maybe some other solution such as finding changelogs in parallel and/or showing the UI and loading the changelogs in the background.

**Comment by vfonic** [comment]
One project:

`bundle outdated  1.85s user 0.37s system 66% cpu 3.363 total`
`bundle ui  4.64s user 0.86s system 14% cpu 38.583 total`

Another project:

`bundle outdated  3.60s user 0.48s system 74% cpu 5.482 total`
`bundle ui  7.84s user 1.25s system 5% cpu 2:37.22 total`

Keep in mind that I ran `time bundle ui` and manually stopped the command when the UI was shown so the total times for `time bundle ui` might be off by a few seconds. Still, the difference is an order of magnitude higher.

**Comment by mattbrictson** [comment]
Thanks for the suggestion! Given my workload at the moment, I don't think I'll be implementing this in the near term, but I am not opposed to a PR if you or someone else wants to take a crack at it.

Of the solutions you proposed, I like the idea of loading the changelogs in the background the best, since it speeds up the initial render without sacrificing functionality.

**Comment by mattbrictson** [comment]
@vfonic FYI, I created a proof-of-concept for fetching changelogs in parallel in PR #68. Let me know if that would address your original concern.
